### ISSUE TITLE
Embedded Apple and Google Pay

### ISSUE THREAD

**Issue by iBobik** [ThePay/api-client#54]
I want to detect if Apple or Google Pay is configured in the browser and show it in the UI of my app.

https://stripe.com/docs/stripe-js/elements/payment-request-button

How to do it with ThePay?

**Comment by Triplkrypl** [comment]
We do not detect availability of Google or Apple pay in a browser and now we not have plan for future implementation. Customer will see these methods every time, if they are active in ThePay system for project.

I can only suggest looking for some third-party library with support for detecting of configured Google or Apple pay. Than list of payment methods returned from ThePay API, can be filtered to remove Google or Apple pay from showed method list if they are not configured in browser.

**Comment by iBobik** [comment]
Detection is the simplest part.

What I ask for is something different:
Ability to trigger OS’s payment dialog from my app frontend without opening
Thepay webpage.

See the Stripe components I linked.

11. 8. 2023 14:47:07, Vojtěch Brožek ***@***.***> napsal:

**Comment by Triplkrypl** [comment]
I apology for misunderstand, but my response will be similar 🙁.
For payment realization customer must be redirected on ThePay webpage, because we redirecting him into another systems in most cases (online methods or 3d secure authentication), also for Google and Apple pay, you can test payment process here: https://www.thepay.eu/cs/test-platby/.

For now only one embedded solution possible without redirecting, is open new dialog and here load ThePay payment page for customer, ideally with pre-selected payment method and customer will see directly payment form or another options dependent on payment method.
